// ─── Seed data for the in-memory store ───────────────────────────
// Mirrors the original static data plus admin user + demo records.

import { randomUUID } from 'crypto';

const now = Date.now();
const dayMs = 86_400_000;

export const seedData = {
  // ─── Catalog ──────────────────────────────────────────────────
  products: [
    {
      id: 'demo-product-1',
      name: 'Multivitamin Complex 60 Capsules',
      shortName: 'Multivitamin Complex',
      brand: 'Himalaya',
      brandId: 'b1',
      price: 24.99,
      oldPrice: 118,
      note: '60 Capsules',
      badge: '15% OFF',
      categoryId: 'cat-vitamins',
      stock: 245,
      reorderLevel: 50,
      sku: 'MED-001',
      status: 'active',
      thumbnail: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8e1e877396d8.jpg',
      gallery: [
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8e1e877396d8.jpg',
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/543934944673.jpg',
      ],
      productType: 'Vitamins & Supplements',
      manufacturer: 'Himalaya Wellness',
      marketer: 'Himalaya Wellness',
      composition: [{ salt: 'Multivitamin Complex', strength: '1000 mg' }],
      dosageForm: 'Capsule',
      strengthValue: '1000',
      strengthUnit: 'mg',
      shortDescription: 'Complete daily multivitamin with 23 essential vitamins and minerals.',
      fullDescription: 'A complete daily multivitamin complex with 23 essential vitamins and minerals to support overall health, immunity, and energy levels. Formulated with optimal dosages of Vitamin A, B-complex, C, D3, E, K, along with key minerals like Zinc, Selenium, and Magnesium.',
      highlights: ['23 essential vitamins & minerals', 'Boosts immunity', 'Supports energy levels', 'Easy-to-swallow capsules'],
      searchKeywords: ['multivitamin', 'vitamins', 'supplement', 'immunity'],
      tags: ['Bestseller', 'Immunity'],
      productStatus: 'Active',
      featured: true,
      bestseller: true,
      storageCondition: 'Room Temperature',
      storageInstructions: 'Store below 25°C in a dry place.',
      uses: 'Daily nutritional support',
      benefits: 'Supports immunity, energy, and overall wellness',
      howToUse: 'Take 1 capsule daily after meals',
      // Legacy
      icon: 'medication',
      tint: '#d9eeee',
      description: 'A complete daily multivitamin complex with 23 essential vitamins and minerals to support overall health, immunity, and energy levels.',
    },
    {
      id: 'demo-product-2',
      name: 'Ashwagandha Extract 500mg 60 Capsules',
      shortName: 'Ashwagandha Extract',
      brand: 'Dabur',
      brandId: 'b3',
      price: 18.5,
      note: '500mg, 60 Capsules',
      categoryId: 'cat-ayurveda',
      stock: 18,
      reorderLevel: 30,
      sku: 'MED-014',
      status: 'active',
      thumbnail: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2786968b2590.jpg',
      gallery: [
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2786968b2590.jpg',
      ],
      productType: 'Ayurveda',
      manufacturer: 'Dabur India',
      marketer: 'Dabur India',
      composition: [{ salt: 'Ashwagandha Extract', strength: '500 mg' }],
      dosageForm: 'Capsule',
      strengthValue: '500',
      strengthUnit: 'mg',
      shortDescription: 'Pure Ashwagandha root extract for stress relief and better sleep.',
      fullDescription: 'Pure Ashwagandha root extract for stress relief, better sleep, and improved cognitive function. Standardized to 5% withanolides for consistent potency.',
      highlights: ['500mg pure extract', '5% withanolides', 'Stress relief', 'Better sleep'],
      searchKeywords: ['ashwagandha', 'stress', 'sleep', 'ayurveda'],
      tags: ['Natural', 'Stress Relief'],
      productStatus: 'Active',
      storageCondition: 'Room Temperature',
      storageInstructions: 'Store in a cool, dry place away from sunlight.',
      uses: 'Stress management, sleep support',
      benefits: 'Reduces stress, improves sleep quality, boosts cognition',
      howToUse: 'Take 1-2 capsules daily with water',
      icon: 'spa',
      tint: '#e7f0df',
      description: 'Pure Ashwagandha root extract for stress relief, better sleep, and improved cognitive function. Standardized to 5% withanolides.',
    },
    {
      id: 'demo-product-3',
      name: 'Advanced Blood Glucose Monitor Kit',
      shortName: 'Blood Glucose Monitor',
      brand: 'Dr. Morepen',
      brandId: 'b4',
      price: 39.99,
      note: 'Complete monitoring kit',
      badge: 'BESTSELLER',
      categoryId: 'cat-healthcare',
      stock: 0,
      reorderLevel: 20,
      sku: 'MED-028',
      status: 'active',
      thumbnail: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d8fb8cfa4c71.jpg',
      gallery: [
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d8fb8cfa4c71.jpg',
      ],
      productType: 'Healthcare Device',
      manufacturer: 'Dr. Morepen',
      marketer: 'Dr. Morepen',
      shortDescription: 'Complete blood glucose monitoring kit with meter and strips.',
      fullDescription: 'Complete blood glucose monitoring kit with meter, 50 test strips, lancets, and carrying case. Results in 5 seconds with high accuracy.',
      highlights: ['Results in 5 seconds', '50 test strips included', 'Memory for 500 readings', 'Carrying case included'],
      searchKeywords: ['glucose', 'diabetes', 'monitor', 'sugar'],
      tags: ['Bestseller', 'Diabetes Care'],
      productStatus: 'Active',
      bestseller: true,
      storageCondition: 'Room Temperature',
      uses: 'Blood glucose monitoring',
      benefits: 'Quick and accurate blood sugar readings',
      howToUse: 'Insert strip, prick finger, apply blood sample',
      icon: 'monitor_heart',
      tint: '#dcecf4',
      description: 'Complete blood glucose monitoring kit with meter, 50 test strips, lancets, and carrying case. Results in 5 seconds.',
    },
    {
      id: 'demo-product-4',
      name: 'Fast Acting Muscle Relief Gel 50g',
      shortName: 'Muscle Relief Gel',
      brand: 'Mamaearth',
      brandId: 'b5',
      price: 14.5,
      note: '50g tube',
      categoryId: 'cat-healthcare',
      stock: 82,
      reorderLevel: 25,
      sku: 'MED-042',
      status: 'active',
      thumbnail: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/49b73fee1d34.jpg',
      gallery: [
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/49b73fee1d34.jpg',
      ],
      productType: 'Personal Care',
      manufacturer: 'Mamaearth',
      marketer: 'Mamaearth',
      dosageForm: 'Gel',
      shortDescription: 'Fast-acting topical gel for muscle and joint pain relief.',
      fullDescription: 'Fast-acting topical gel for muscle and joint pain relief. Contains menthol and methyl salicylate for soothing cool-warm therapy.',
      highlights: ['Fast-acting formula', 'Cool-warm therapy', '50g tube', 'Non-greasy'],
      searchKeywords: ['pain relief', 'muscle', 'gel', 'joint pain'],
      tags: ['Pain Relief'],
      productStatus: 'Active',
      storageCondition: 'Room Temperature',
      uses: 'Muscle and joint pain relief',
      benefits: 'Quick relief from muscle pain and stiffness',
      howToUse: 'Apply generously on affected area 2-3 times daily',
      icon: 'healing',
      tint: '#f2e4d7',
      description: 'Fast-acting topical gel for muscle and joint pain relief. Contains menthol and methyl salicylate for soothing cool-warm therapy.',
    },
    {
      id: 'demo-product-5',
      name: 'Vitamin D3 5000 IU Softgels 120ct',
      shortName: 'Vitamin D3 5000 IU',
      brand: 'HealthKart',
      brandId: 'b8',
      price: 12.99,
      oldPrice: 19.99,
      note: '120 Softgels',
      categoryId: 'cat-vitamins',
      stock: 320,
      reorderLevel: 60,
      sku: 'MED-055',
      status: 'active',
      thumbnail: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/543934944673.jpg',
      gallery: [
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/543934944673.jpg',
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8e1e877396d8.jpg',
      ],
      productType: 'Vitamins & Supplements',
      manufacturer: 'HealthKart',
      marketer: 'HealthKart',
      composition: [{ salt: 'Vitamin D3 (Cholecalciferol)', strength: '5000 IU' }],
      dosageForm: 'Capsule',
      strengthValue: '5000',
      strengthUnit: 'IU',
      shortDescription: 'High potency Vitamin D3 for bone health and immunity.',
      fullDescription: 'High potency Vitamin D3 supplement for bone health, immune support, and mood regulation. Daily dose supports calcium absorption.',
      highlights: ['5000 IU high potency', '120 softgels', 'Supports bone health', 'Boosts immunity'],
      searchKeywords: ['vitamin d3', 'bone health', 'immunity', 'supplement'],
      tags: ['Bestseller', 'Immunity'],
      productStatus: 'Active',
      bestseller: true,
      storageCondition: 'Protect from Light',
      storageInstructions: 'Store in a cool, dry place away from direct sunlight.',
      uses: 'Vitamin D deficiency, bone health',
      benefits: 'Supports calcium absorption, bone health, immune function',
      howToUse: 'Take 1 softgel daily with a meal',
      icon: 'pill',
      tint: '#fef3c7',
      description: 'High potency Vitamin D3 supplement for bone health, immune support, and mood regulation. Daily dose supports calcium absorption.',
    },
    {
      id: 'demo-product-6',
      name: 'Omeprazole 20mg Delayed Release 42 Tablets',
      shortName: 'Omeprazole 20mg',
      brand: 'Himalaya',
      brandId: 'b1',
      price: 22.5,
      note: '42 Tablets',
      badge: 'PRESCRIPTION',
      categoryId: 'cat-prescription',
      stock: 95,
      reorderLevel: 30,
      sku: 'MED-070',
      status: 'active',
      thumbnail: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/56be4da27a25.jpg',
      gallery: [
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/56be4da27a25.jpg',
      ],
      productType: 'Medicine',
      manufacturer: 'Himalaya Wellness',
      marketer: 'Himalaya Wellness',
      composition: [{ salt: 'Omeprazole', strength: '20 mg' }],
      dosageForm: 'Tablet',
      strengthValue: '20',
      strengthUnit: 'mg',
      routeOfAdministration: 'Oral',
      schedule: 'Schedule H',
      shortDescription: 'Prescription medication for frequent heartburn.',
      fullDescription: 'Prescription medication for frequent heartburn. Taken once daily for 14 days. Requires valid prescription.',
      highlights: ['20mg delayed release', '42 tablets pack', 'For frequent heartburn', 'Once daily dosing'],
      searchKeywords: ['omeprazole', 'heartburn', 'acidity', 'prescription'],
      tags: ['Prescription'],
      productStatus: 'Active',
      storageCondition: 'Room Temperature',
      storageInstructions: 'Store below 25°C, protect from moisture.',
      uses: 'Frequent heartburn, GERD',
      benefits: 'Reduces stomach acid production',
      howToUse: 'Take 1 tablet daily before breakfast',
      precautions: 'Consult doctor if pregnant or breastfeeding',
      sideEffects: 'Headache, nausea, diarrhea',
      icon: 'medication',
      tint: '#fee2e2',
      description: 'Prescription medication for frequent heartburn. Taken once daily for 14 days. Requires valid prescription.',
      prescriptionRequired: true,
    },
    {
      id: 'demo-product-7',
      name: 'Digital Infrared Forehead Thermometer',
      shortName: 'IR Thermometer',
      brand: 'Dr. Morepen',
      brandId: 'b4',
      price: 29.99,
      note: 'Non-contact IR',
      categoryId: 'cat-healthcare',
      stock: 45,
      reorderLevel: 15,
      sku: 'MED-088',
      status: 'active',
      thumbnail: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/5dd31878ae3a.jpg',
      gallery: [
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/5dd31878ae3a.jpg',
      ],
      productType: 'Healthcare Device',
      manufacturer: 'Dr. Morepen',
      marketer: 'Dr. Morepen',
      shortDescription: 'Professional-grade non-contact infrared thermometer.',
      fullDescription: 'Professional-grade infrared forehead thermometer with 1-second reading, fever alarm, and memory for 32 readings.',
      highlights: ['1-second reading', 'Non-contact', 'Fever alarm', '32 readings memory'],
      searchKeywords: ['thermometer', 'fever', 'temperature', 'ir'],
      tags: ['Healthcare Device'],
      productStatus: 'Active',
      storageCondition: 'Room Temperature',
      uses: 'Body temperature measurement',
      benefits: 'Quick, accurate, non-contact temperature reading',
      howToUse: 'Point at forehead, press button, read result',
      icon: 'thermostat',
      tint: '#dbeafe',
      description: 'Professional-grade infrared forehead thermometer with 1-second reading, fever alarm, and memory for 32 readings.',
    },
    {
      id: 'demo-product-8',
      name: 'Hand Sanitizer Gel 500ml with Aloe',
      shortName: 'Hand Sanitizer 500ml',
      brand: 'Mamaearth',
      brandId: 'b5',
      price: 6.99,
      note: '500ml with Aloe',
      badge: 'VALUE',
      categoryId: 'cat-winter-care',
      stock: 540,
      reorderLevel: 100,
      sku: 'MED-100',
      status: 'active',
      thumbnail: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/49b73fee1d34.jpg',
      gallery: [
        'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/49b73fee1d34.jpg',
      ],
      productType: 'Personal Care',
      manufacturer: 'Mamaearth',
      marketer: 'Mamaearth',
      shortDescription: '70% alcohol hand sanitizer with moisturizing aloe vera.',
      fullDescription: '70% alcohol-based hand sanitizer with moisturizing aloe vera. Kills 99.9% of germs without drying skin.',
      highlights: ['70% alcohol', 'Kills 99.9% germs', 'With aloe vera', '500ml bottle'],
      searchKeywords: ['sanitizer', 'hand wash', 'hygiene', 'alcohol'],
      tags: ['Value', 'Hygiene'],
      productStatus: 'Active',
      storageCondition: 'Room Temperature',
      uses: 'Hand hygiene',
      benefits: 'Kills germs, moisturizes skin',
      howToUse: 'Apply enough to cover hands, rub until dry',
      icon: 'sanitizer',
      tint: '#dcfce7',
      description: '70% alcohol-based hand sanitizer with moisturizing aloe vera. Kills 99.9% of germs without drying skin.',
    },
  ],

  // ─── Categories ───────────────────────────────────────────────
  categories: [
    { id: 'cat-prescription', name: 'Prescription Meds', icon: 'medication', tint: '#fee2e2', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-vitamins', name: 'Vitamins & Supplements', icon: 'pill', tint: '#f3e5f5', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-ayurveda', name: 'Ayurveda', icon: 'spa', tint: '#f1f8e9', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-homeopathy', name: 'Homeopathy', icon: 'medication', tint: '#e8f5e9', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-healthcare', name: 'Healthcare Devices', icon: 'monitor_heart', tint: '#e1f5fe', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-sexual-wellness', name: 'Sexual Wellness', icon: 'favorite', tint: '#fff3e0', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-winter-care', name: 'Winter Care', icon: 'ac_unit', tint: '#e0f7fa', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-diabetes', name: 'Diabetes Care', icon: 'bloodtype', tint: '#fff8e1', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-skin-care', name: 'Skin Care', icon: 'face', tint: '#f1f8e9', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-elderly-care', name: 'Elderly Care', icon: 'elderly', tint: '#fff3e0', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-supplements', name: 'Supplements', icon: 'fitness_center', tint: '#ffe0b2', productCount: 0, visibility: 'active', updatedAt: now },
    { id: 'cat-health-food', name: 'Health Food', icon: 'nutrition', tint: '#fbe9e7', productCount: 0, visibility: 'active', updatedAt: now },
  ],

  // ─── Health Concerns ──────────────────────────────────────────
  healthConcerns: [
    { id: 'hc-1', name: 'Diabetes care', icon: 'bloodtype', tint: '#eadff3', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/a986a6ceacf1.jpg', visibility: 'active' },
    { id: 'hc-2', name: 'Cardiac care', icon: 'favorite', tint: '#f6dfe4', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/83b62edcd547.png', visibility: 'active' },
    { id: 'hc-3', name: 'Pain relief', icon: 'healing', tint: '#dcecf4', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/756baf8168ba.jpg', visibility: 'active' },
    { id: 'hc-4', name: 'Kidney care', icon: 'kidney', tint: '#f6e4d6', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/6146c606ff80.jpg', visibility: 'active' },
    { id: 'hc-5', name: 'Muscle care', icon: 'fitness_center', tint: '#d9eeee', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8355dc8ba472.jpg', visibility: 'active' },
    { id: 'hc-6', name: 'Liver care', icon: 'medical_information', tint: '#f2d9d9', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/c4ccb7e3d01a.jpg', visibility: 'active' },
    { id: 'hc-7', name: 'Respiratory care', icon: 'air', tint: '#dbeafe', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/3919e491e919.jpg', visibility: 'active' },
    { id: 'hc-8', name: 'Eye care', icon: 'visibility', tint: '#fef3c7', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f108b2802ada.jpg', visibility: 'active' },
    { id: 'hc-9', name: 'Mental Wellness', icon: 'psychology', tint: '#ede9fe', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e2d25377b9e3.jpg', visibility: 'active' },
  ],

  // ─── Brands ───────────────────────────────────────────────────
  brands: [
    { id: 'b1', name: 'Himalaya', logo: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/14f33d08f0a6.jpg', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/14f33d08f0a6.jpg', visibility: 'active' },
    { id: 'b2', name: 'Horlicks', logo: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ede9e0b9232e.jpg', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ede9e0b9232e.jpg', visibility: 'active' },
    { id: 'b3', name: 'Dabur', logo: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4aaf5fa19cb0.png', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4aaf5fa19cb0.png', visibility: 'active' },
    { id: 'b4', name: 'Dr. Morepen', logo: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2ac43e4b5b62.jpg', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2ac43e4b5b62.jpg', visibility: 'active' },
    { id: 'b5', name: 'Mamaearth', logo: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/14447521fa7f.jpg', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/14447521fa7f.jpg', visibility: 'active' },
    { id: 'b6', name: 'Bournvita', logo: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/3680857aed58.jpg', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/3680857aed58.jpg', visibility: 'active' },
    { id: 'b7', name: 'JIVA', logo: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/cb785d94a4c1.jpg', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/cb785d94a4c1.jpg', visibility: 'active' },
    { id: 'b8', name: 'HealthKart', logo: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e451c26bfbe2.jpg', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e451c26bfbe2.jpg', visibility: 'active' },
  ],

  // ─── Offers ───────────────────────────────────────────────────
  offers: [
    { id: 'o1', text: 'Flat 25% off + up to $10 cashback', code: 'MEDI25', visibility: 'active' },
    { id: 'o2', text: 'Free delivery on orders above $50', code: 'FREE50', visibility: 'active' },
    { id: 'o3', text: 'Buy 2 Get 1 Free on Vitamins', code: 'B2G1', visibility: 'active' },
  ],

  // ─── Home banners (controlled from admin) ─────────────────────
  banners: [
    { id: 'banner-hero', slot: 'hero', title: 'Boost your immunity', subtitle: 'Health essentials for brighter days.', ctaText: 'CLICK TO SHOP', ctaHref: '/products', badge: 'Everyday wellness', imageUrl: '/banner-hero.png', visibility: 'active' },
    { id: 'banner-prescription', slot: 'prescription', title: 'Order with prescription', subtitle: 'Upload a prescription and tell us what you need. We do the rest!', ctaText: 'Order Now', ctaHref: '/prescriptions', note: 'Flat 25% off on medicines*', visibility: 'active' },
    { id: 'banner-essentials', slot: 'essentials', title: 'Essentials', subtitle: 'Daily health', ctaText: 'SHOP NOW', ctaHref: '/products', note: 'UP TO 30% off', imageUrl: '/banner-essentials.png', visibility: 'active' },
    { id: 'banner-call', slot: 'call', title: 'Call to order medicines', subtitle: 'Need medicine without any hassle? call us now', ctaText: 'Call Now', ctaHref: '', visibility: 'active' },
  ],

  // ─── Lab packages & tests ─────────────────────────────────────
  labPackages: [
    { id: 'full-body-checkup', name: 'Full Body Checkup', detail: 'Includes 85 tests: CBC, Thyroid, Lipid, Liver & more.', price: 149, icon: 'favorite', badge: '50% OFF', visibility: 'active', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2586d3fab709.png' },
    { id: 'cardiac-profile', name: 'Cardiac Profile', detail: 'Complete heart health evaluation and lipid panel.', price: 89, icon: 'ecg_heart', visibility: 'active', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/4d034f06dab5.webp' },
    { id: 'womens-health', name: "Women's Health", detail: 'Essential screening including Iron, Thyroid, Vitamin D.', price: 120, icon: 'woman', visibility: 'active', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/758ffc3de39a.jpg' },
    { id: 'diabetic-screening', name: 'Diabetic Screening', detail: 'HbA1c, Fasting Sugar, and vital organ screening.', price: 45, icon: 'bloodtype', badge: 'Popular', visibility: 'active', imageUrl: 'https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/40f3c239fc55.jpg' },
  ],
  labTests: [
    { id: 'lt1', name: 'Complete Blood Count (CBC)', detail: 'Results in 24 hrs', price: 15, visibility: 'active' },
    { id: 'lt2', name: 'Thyroid Profile (T3, T4, TSH)', detail: 'Results in 24 hrs', price: 25, visibility: 'active' },
    { id: 'lt3', name: 'Lipid Profile', detail: 'Fasting required', price: 20, visibility: 'active' },
    { id: 'lt4', name: 'Vitamin D Test', detail: 'Results in 48 hrs', price: 35, visibility: 'active' },
    { id: 'lt5', name: 'HbA1c Diabetes Test', detail: 'No fasting required', price: 28, visibility: 'active' },
  ],

  // ─── Demo orders (visible to admin) ───────────────────────────
  orders: [
    {
      id: 'MD-8492-X',
      userId: 'u1',
      customerName: 'Health User',
      customerEmail: 'user@medidemo.com',
      items: [{ productId: 'demo-product-1', name: 'Multivitamin Complex', qty: 3, price: 24.99 }],
      total: 142.50,
      shippingAddress: '123 Wellness Avenue',
      status: 'Delivered',
      type: 'medicine',
      prescriptionVerified: true,
      createdAt: now - dayMs * 2,
    },
    {
      id: 'MD-8498-K',
      userId: 'u2',
      customerName: 'Ava Morgan',
      customerEmail: 'ava@example.com',
      items: [{ name: 'Full Body Checkup', qty: 1, price: 149 }],
      total: 149.00,
      shippingAddress: '48 Park Lane',
      status: 'Processing',
      type: 'lab',
      prescriptionVerified: false,
      createdAt: now - dayMs,
    },
    {
      id: 'MD-8501-Q',
      userId: 'u3',
      customerName: 'Marcus Chen',
      customerEmail: 'marcus@example.com',
      items: [
        { productId: 'demo-product-5', name: 'Vitamin D3 5000 IU', qty: 1, price: 12.99 },
        { productId: 'demo-product-1', name: 'Multivitamin Complex', qty: 1, price: 24.99 },
      ],
      total: 37.98,
      shippingAddress: '78 Healthway Ave',
      status: 'In Transit',
      type: 'medicine',
      prescriptionVerified: false,
      createdAt: now - 36_00_000,
    },
    {
      id: 'MD-8508-P',
      userId: 'u4',
      customerName: 'Elena Stone',
      customerEmail: 'elena@example.com',
      items: [{ productId: 'demo-product-3', name: 'Blood Glucose Monitor', qty: 1, price: 39.99 }],
      total: 64.50,
      shippingAddress: '90 Madison Street',
      status: 'Cancelled',
      type: 'medicine',
      prescriptionVerified: false,
      createdAt: now - dayMs * 3,
    },
    {
      id: 'LB-1001',
      userId: 'u1',
      customerName: 'Health User',
      customerEmail: 'user@medidemo.com',
      items: [{ name: 'Full Body Checkup', qty: 1, price: 149 }],
      total: 149.00,
      shippingAddress: '123 Wellness Avenue',
      status: 'Confirmed',
      type: 'lab',
      scheduledAt: now + dayMs,
      prescriptionVerified: false,
      createdAt: now - 7200_000,
    },
    {
      id: 'LB-1002',
      userId: 'u2',
      customerName: 'Ava Morgan',
      customerEmail: 'ava@example.com',
      items: [{ name: 'Thyroid Profile', qty: 1, price: 25 }],
      total: 25.00,
      shippingAddress: '48 Park Lane',
      status: 'Processing',
      type: 'lab',
      scheduledAt: now + 36_00_000,
      prescriptionVerified: false,
      createdAt: now - 5400_000,
    },
  ],

  // ─── Demo users (customer accounts) ───────────────────────────
  users: [
    { id: 'u1', name: 'Health User', email: 'user@medidemo.com', role: 'patient', status: 'active', phone: '+1 555-0100', lastLogin: now - 36_00_000 },
    { id: 'u2', name: 'Ava Morgan', email: 'ava@example.com', role: 'patient', status: 'active', phone: '+1 555-0101', lastLogin: now - dayMs },
    { id: 'u3', name: 'Marcus Chen', email: 'marcus@example.com', role: 'patient', status: 'active', phone: '+1 555-0102', lastLogin: now - dayMs * 2 },
    { id: 'u4', name: 'Elena Stone', email: 'elena@example.com', role: 'patient', status: 'blocked', phone: '+1 555-0103', lastLogin: now - dayMs * 5 },
    { id: 'u5', name: 'David Chen', email: 'david@example.com', role: 'lab_tech', status: 'active', phone: '+1 555-0104', lastLogin: now - dayMs * 3 },
    { id: 'u6', name: 'Dr. Sarah Jenkins', email: 'sarah@example.com', role: 'doctor', status: 'active', phone: '+1 555-0105', lastLogin: now - 36_00_000 },
  ],

  // ─── Employees (staff managed by admin) ───────────────────────
  employees: [
    { id: 'e1', name: 'Sarah Jenkins', email: 'sarah@example.com', department: 'Pharmacists', status: 'active', joinedAt: '2024-01-12', phone: '+1 555-0200' },
    { id: 'e2', name: 'Michael Chang', email: 'michael@example.com', department: 'Lab Technicians', status: 'active', joinedAt: '2024-03-06', phone: '+1 555-0201' },
    { id: 'e3', name: 'David Miller', email: 'dmiller@example.com', department: 'Delivery Partners', status: 'active', joinedAt: '2024-04-21', phone: '+1 555-0202' },
    { id: 'e4', name: 'Priya Shah', email: 'priya@example.com', department: 'Admin', status: 'pending', joinedAt: '2024-06-14', phone: '+1 555-0203' },
  ],

  // ─── Support tickets ──────────────────────────────────────────
  supportTickets: [
    { id: 'SUP-2201', userId: 'u1', customerName: 'Health User', subject: 'Prescription verification', priority: 'High', status: 'Open', message: 'Need help verifying my uploaded prescription for Omeprazole.', createdAt: now - 7200_000 },
    { id: 'SUP-2202', userId: 'u2', customerName: 'Ava Morgan', subject: 'Delivery time change', priority: 'Medium', status: 'In Progress', message: 'Can my delivery be moved to tomorrow morning?', createdAt: now - dayMs },
    { id: 'SUP-2203', userId: 'u3', customerName: 'Marcus Chen', subject: 'Refund request', priority: 'High', status: 'Open', message: 'Order #MD-8508-P was cancelled. Requesting refund.', createdAt: now - dayMs * 2 },
    { id: 'SUP-2204', userId: 'u4', customerName: 'Elena Stone', subject: 'Lab report question', priority: 'Low', status: 'Pending', message: 'Question about my CBC report results.', createdAt: now - dayMs * 3 },
  ],

  // ─── Transactions (derived from orders) ───────────────────────
  transactions: [
    { id: 'TXN-78421', orderId: 'MD-8492-X', customerName: 'Health User', method: 'Visa •••• 4242', amount: 142.50, status: 'Completed', createdAt: now - dayMs * 2 },
    { id: 'TXN-78422', orderId: 'MD-8498-K', customerName: 'Ava Morgan', method: 'UPI', amount: 149.00, status: 'Completed', createdAt: now - dayMs },
    { id: 'TXN-78423', orderId: 'LB-1003', customerName: 'Marcus Chen', method: 'Wallet', amount: 25.00, status: 'Pending', createdAt: now - 36_00_000 },
    { id: 'TXN-78424', orderId: 'MD-8508-P', customerName: 'Elena Stone', method: 'Visa •••• 8801', amount: 64.50, status: 'Refunded', createdAt: now - dayMs * 3 },
  ],

  // ─── Site settings (admin controlled) ─────────────────────────
  settings: [
    { id: 'site', siteName: 'Balaji Medical Store', tagline: 'Everyday wellness', supportPhone: '+1 555-1234', supportEmail: 'support@medidemo.com', currency: 'USD', currencySymbol: '$', freeShippingThreshold: 50, prescriptionDiscountPct: 25, heroBadgeText: 'Everyday wellness', heroTitle: 'Boost your immunity', heroSubtitle: 'Health essentials for brighter days.', maintenanceMode: false, labTestServiceStart: '09:00', labTestServiceEnd: '21:00', labTestMaxBookingsPerDay: 1, razorpayKeyId: '', razorpayKeySecret: '', razorpayEnabled: false, codEnabled: true, upiEnabled: false, cardEnabled: false },
  ],

  // ─── Auth users (for mock auth only) ──────────────────────────
  authUsers: [
    // Default admin account (email/password: admin@medidemo.com / admin123)
    {
      id: 'admin-1',
      email: 'admin@medidemo.com',
      // NOTE: in mock mode we accept any password matching the demo value.
      password: 'admin123',
      name: 'Admin User',
      role: 'admin',
      status: 'active',
    },
    {
      id: 'user-1',
      email: 'user@medidemo.com',
      password: 'user123',
      name: 'Health User',
      role: 'patient',
      status: 'active',
    },
  ],
};
